# Generated by Django 4.2.29 on 2026-04-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
