# Generated by Django 4.2.29 on 2026-04-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp', '0002_login_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='password',
        ),
    ]
